// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLcf5IpT34vEBgLFdbhzWxVImxEUwtHQ',
    appId: '1:676839232367:web:9e3b34c9edc2d5c447ce9a',
    messagingSenderId: '676839232367',
    projectId: 'drive-mate-bd887',
    authDomain: 'drive-mate-bd887.firebaseapp.com',
    storageBucket: 'drive-mate-bd887.firebasestorage.app',
    measurementId: 'G-J1NG8BLKE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWhRF4YO7HqZyYLjRVBj6tbr7s4XsXaU',
    appId: '1:676839232367:android:29a3284d5db130b847ce9a',
    messagingSenderId: '676839232367',
    projectId: 'drive-mate-bd887',
    storageBucket: 'drive-mate-bd887.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd_oEwX1fbZ-kiPfXB8kIIv0vIQq4sqS4',
    appId: '1:676839232367:ios:bc8c97c95f309c5247ce9a',
    messagingSenderId: '676839232367',
    projectId: 'drive-mate-bd887',
    storageBucket: 'drive-mate-bd887.firebasestorage.app',
    iosBundleId: 'com.drivemate.driveMate',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd_oEwX1fbZ-kiPfXB8kIIv0vIQq4sqS4',
    appId: '1:676839232367:ios:bc8c97c95f309c5247ce9a',
    messagingSenderId: '676839232367',
    projectId: 'drive-mate-bd887',
    storageBucket: 'drive-mate-bd887.firebasestorage.app',
    iosBundleId: 'com.drivemate.driveMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArLcf5IpT34vEBgLFdbhzWxVImxEUwtHQ',
    appId: '1:676839232367:web:a4c01e626da5978647ce9a',
    messagingSenderId: '676839232367',
    projectId: 'drive-mate-bd887',
    authDomain: 'drive-mate-bd887.firebaseapp.com',
    storageBucket: 'drive-mate-bd887.firebasestorage.app',
    measurementId: 'G-J7SX5B6K2N',
  );
}
